### PR TITLE
feat: use isReflectNil instead of isEmptyValue to gate Transformers

### PR DESCRIPTION
**Pull request by GGabriele**
Original upstream PR with reasoning behind this patch: https://github.com/imdario/mergo/pull/203

Couple of additional comments:
- this change doesn't affect the normal behaviour of `mergo` (see below), but it only affects how transformers are gated
- since custom transformers need to match data types in order to execute, this shouldn't affect any existing transformers either

```
$ go test -race ./... -count=1
ok  	github.com/imdario/mergo	0.418s
```

### CODE REVIEW

**Comment by GGabriele** [comment]
Not sure what's going on with travis, as same tests are passing locally :\

**Comment by hbagdi** [comment]
Can you dig deeper to see if there are versions that are not matching up?

**Comment by GGabriele** [comment]
I added a build matrix for various releases of go and it seems this works with >= 1.13

I see [1.13](https://go.dev/doc/go1.13) introduced some changes to the reflect package, maybe that's related

**Comment by hbagdi** [comment]
I'm not familiar with this codebase so can't review. I'll trust you with this one for now.
Some changes:
- Let's test on Go 1.13 and above and get the CI green again.
- Squash into a single commit and capture all the context in the commit body, with links to Github issues where needed. A 100-line commit message body is not a problem ever.

**Comment by GGabriele** [comment]
> I'm not familiar with this codebase so can't review. I'll trust you with this one for now. Some changes:
> 
> * Let's test on Go 1.13 and above and get the CI green again.
> * Squash into a single commit and capture all the context in the commit body, with links to Github issues where needed. A 100-line commit message body is not a problem ever.

Done!

**Comment by hbagdi** [comment]
Go ahead and merge and do a release.

**Pull request merged**
